from Repository import DataBaseConfiguration
_DataBaseConfiguration = DataBaseConfiguration
from Repository import DataBaseConnection
_DataBaseConnection = DataBaseConnection.DataBaseConnection

from Repository import RawTextRepository
_RawTextRepository = RawTextRepository.RawTextRepository
from Repository import TextCollectionMetaRepository
_TextCollectionMetaRepository = TextCollectionMetaRepository.TextCollectionMetaRepository
from Repository import DetectionRepository
_DetectionRepository = DetectionRepository.DetectionRepository
from Repository import RawTextExcerptLocationRepository
_RawTextExcerptLocationRepository = RawTextExcerptLocationRepository.RawTextExcerptLocationRepository
from Repository import RawTextPairRepository
_RawTextPairRepository = RawTextPairRepository.RawTextPairRepository
from Repository import PanRepository
_PanRepository = PanRepository.PanRepository
