
PAIRS_FILE_NAME = 'pairs'
SOURCE_RAW_TEXTS_FOLDER = 'src'
SUSPICIOUS_RAW_TEXT_FOLDER = 'susp'
RANDOM_OBFUSCATION_DETECTION_FOLDER = '03-random-obfuscation'
NO_OBFUSCATION_DETECTION_FOLDER = '02-no-obfuscation'
NO_PLAGIARISM_DETECTION_FOLDER = '01-no-plagiarism'