from Process import BaseProcess
_BaseProcess = BaseProcess.BaseProcess
from Process import PreProcessingRawTextProcess
_PreProcessingRawTextProcess = PreProcessingRawTextProcess.PreProcessingRawTextProcess
from Process import DataImportationProcess
_DataImportationProcess = DataImportationProcess.DataImportationProcess