from Internal import AdaboostInternalProcess
_AdaboostInternalProcess = AdaboostInternalProcess.AdaboostInternalProcess
from Internal import BagOfTokensInternalProcess
_BagOfTokensInternalProcess = BagOfTokensInternalProcess.BagOfTokensInternalProcess
from Internal import ExcerptInternalProcess
_ExcerptInternalProcess = ExcerptInternalProcess.ExcerptInternalProcess
from Internal import PlagiarismDetectionInternalProcess
_PlagiarismDetectionInternalProcess = PlagiarismDetectionInternalProcess.PlagiarismDetectionInternalProcess
from Internal import RawTextInternalProcess
_RawTextInternalProcess = RawTextInternalProcess.RawTextInternalProcess
from Internal import TokenInternalProcess
_TokenInternalProcess = TokenInternalProcess.TokenInternalProcess